### ISSUE TITLE
[PE-D][Tester B] Image in the UG is not formatted 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-2/tp#126] opened 2024-04-05 18:23 UTC
`tag.PNG`
This image in the UG does not show. Perhaps the image does not exist in the docs folder anymore, not sure what the error is exactly.

![image.png](https://raw.githubusercontent.com/kinjalagarwal1810/ped/main/files/cacaa1a3-c2b3-45f0-b43d-18bfe1486c5f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kinjalagarwal1810/ped#7

**Comment by miffi** [comment] 2024-04-11 12:44
Duplicate of #110

**Closed by miffi** 2024-04-11 12:44 UTC
